### ISSUE TITLE
Publishing checklist

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1]
Before publishing:

- [x] Update agent to support new `context.db` format
- [x] Update agent to support new `serverUrl` config param
- [x] Publish agent to npm
- [x] Update README of https://github.com/elastic/apm-nodejs-http-client to point to this repo

After publishing:

- [x] Add link to blog post to README
