### ISSUE TITLE
Look into using MongoDB APM API in the mongodb module

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#142]
Version 3 of the Node.js MongoDB driver have just been released and we need to add support for it, but instead of simply upgrading our existing instrumentation, we should consider changing how we instrument MongoDB.

We currently patch the [mongodb-core](https://github.com/mongodb-js/mongodb-core) module, which is the underlying module used by the official [mongodb](https://github.com/mongodb/node-mongodb-native) module. Most 3rd party MongoDB modules depends on the main mongodb module, but we decided to target the more low level mongodb-core module since the [mongojs](https://github.com/mafintosh/mongojs) module used to use that directly instead of mongodb. Recently however mongojs have switched to use the mongodb module as well.

The mongodb module have an official APM API that means we don't have to patch anything. This means more stability and easier support for future MongoDB releases.

You can read about the MongoDB APM API here:

- MongoDB 2.x: http://mongodb.github.io/node-mongodb-native/2.0/reference/management/apm/
- MongoDB 3.x: http://mongodb.github.io/node-mongodb-native/3.0/reference/management/apm/

#### Tasks

- [x] Validate if we can get the same level of insights as we have today if we switch to using the APM API
- [ ] Get overview of time involved to switch to the APM API
- [ ] Create new GitHub issues accordingly

**Comment by watson** [comment]
Added support for version 3 of the mongodb-core module via #190

**Comment by Qard** [comment]
Should this be closed, since the patches cover v3, or do we still want to consider using the official APM API?

**Comment by watson** [comment]
I think it still makes sense to use the official API if it can give us the metrics that we want. It's always better than monkey patching 😅

**Comment by Qard** [comment]
I've reviewed how the APM API works and it looks like it _can_ do everything we need, and without too much effort. However, the patches applied are much heavier and more extensive than what we do currently. I suspect there may be somewhat significant overhead to using the APM API.

**Comment by watson** [comment]
Would you recommend that we just close this issue for now then?

**Comment by alvarolobato** [comment]
We've decided to keep our current instrumentation for now. See Stephen's comment.
