### ISSUE TITLE
[meta][docs] Documentation restructure

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-agent-nodejs#1427]
A meta issue for tracking documentation improvements outlined in https://github.com/elastic/apm-dev/issues/425.

**https://github.com/elastic/apm-agent-nodejs/pull/1435**
- [x] Add release notes to the documentation: https://github.com/elastic/apm/issues/132

**https://github.com/elastic/apm-agent-nodejs/pull/1428**
- [x] Top level heading and doc sync for log correlation: https://github.com/elastic/apm/issues/149
- [x] Use shared version attributes: https://github.com/elastic/apm/issues/150
- [x] Add a section on how the Agent does instrumentation: https://github.com/elastic/apm/issues/146
- [x] Rename the APM UI to "APM app": https://github.com/elastic/apm-dev/issues/567
- [x] Updates to the new documentation structure outlined [here](https://docs.google.com/spreadsheets/d/1P53LbNY7jFSLLJhOKw-nmDenQbrIFlY4EEFJGqT1kmY/edit#gid=0)
- [x] Closes https://github.com/elastic/apm-agent-nodejs/issues/1023.
- [x] Sync Central config docs: https://github.com/elastic/apm-agent-dotnet/pull/497#discussion_r326303325

**Comment by bmorelli25** [comment]
Thanks @Qard for your help and patience. One Agent done!
