### ISSUE TITLE
[META 448] Auto-infer destination.service.resource and adapt public API

### ISSUE THREAD

**Issue by elastic-apm-tech** [elastic/apm-agent-nodejs#2103]
As described in https://github.com/elastic/apm/issues/448, the agent needs to apply the following changes to comply with the current SPEC for destination fields:

- [ ] Infer destination.service.resource based on other fields
- [ ] Add a public API to set destination.service.resource
- [ ] As destination.service.name and destination.service.type are not used anywhere in the product, I propose to deprecate and remove them also in the public API (if already added there)
- [ ] Add a public API to start an exit span. This auto-infers the destination.service.resource based on the subtype if not set otherwise. Avoids creating nested exit spans and makes the service map work with those custom spans by default, without having to set any destination fields.

**Comment by trentm** [comment]
> Add a public API to set destination.service.resource

Go has a `func (c *SpanContext) SetDestinationService(service DestinationServiceSpanContext) {`.

Java has a `Span setDestinationService(String)`

Python checks on serialization of a span if `nested_key(self.context, "destination", "service", "resource")` is already set.
