### ISSUE TITLE
[META 497] Collecting statistics about dropped spans

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-nodejs#2302]
As described in [this spec](https://github.com/elastic/apm/blob/master/specs/agents/handling-huge-traces/tracing-spans-dropped-stats.md), agents should collect statistics on dropped spans.

Meta issue: [![issue details](https://img.shields.io/endpoint?url=https%3A%2F%2Fgiss.app.elstc.co%2Fapi%2Fstatus%2Felastic%2Fapm%2F497)](https://github.com/elastic/apm/issues/497)

**Comment by astorm** [comment]
Looking at [the spec](https://github.com/elastic/apm/blob/main/specs/agents/handling-huge-traces/tracing-spans-dropped-stats.md) and using the java agent's implementation as a reference, it looks like span statistics make the assumption that even a span that's not kept still exists for the lifetime of a transaction.  Specifically, the statistics include data that's only avaiable at span end (the `duration.sum.us` property).  The Node Agent's current implementation doesn't share this assumption.

ex. when the Node.js agent exceeds the transaction-max-spans limit, our [`createSpan` method](https://github.com/elastic/apm-agent-nodejs/blob/e2be0dabf8842865a4f43722baf3d1d7ad609165/lib/instrumentation/transaction.js#L136-L139) skips creating a span.  However, in the same transaction-max-spans scenario in the java agent, [we mark the span as not recorded (aka not sampled)](https://github.com/elastic/apm-agent-java/blob/56f986ca38bdfbc03bf97070cc40547f715defd9/apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/Span.java#L103-L114), and it's not until the tracer's `endSpan` method that [the sampled flag is checked](https://github.com/elastic/apm-agent-java/blob/56f986ca38bdfbc03bf97070cc40547f715defd9/apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracer.java#L393-L399) and an early return prevents the span from being sent.  (you can also see [the code calls `captureDroppedSpan`](https://github.com/elastic/apm-agent-java/blob/56f986ca38bdfbc03bf97070cc40547f715defd9/apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracer.java#L396) and that [this method](https://github.com/elastic/apm-agent-java/blob/56f986ca38bdfbc03bf97070cc40547f715defd9/apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/Transaction.java#L245) eventually [records the stats](https://github.com/elastic/apm-agent-java/blob/56f986ca38bdfbc03bf97070cc40547f715defd9/apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/DroppedSpanStats.java#L119) for both count and duraction) 

Therefore, in order to implement span statistics, we'll need to change our implementation such that spans _are_ created but their context marked to indicate that recorded/sampled=false when transaction-max-span is exceeded _and to not_ report spans that are unsampled.  

Work to be done

- [ ] Implement a `setRecorded` method for our TraceContext and TraceParent object(s) (using the traceparent flags)
- [ ] Change `transactionMaxSpans` check to no longer return `null`early, instead create the the span but call `setRecorded(false)`. Also, we'll add add an additional check in span end to prevent recording of unsampled spans (Risk/Unknown: Where to add this check? In `span.end`?  or `instrumentation.addEndedSpan`? Or just block `_encodeAndSendSpan`?  Or some other thing?  What will the effect be now doing all the additional span ending work be?)
- [ ] Implement logic to capture span statistics when sampling or dropping a span. Serialize these statistics on transaction end.
