### ISSUE TITLE
APM Server Reporting "400 - data validation error" -- missing metadata field

### ISSUE THREAD

**Issue by astorm** [elastic/apm-agent-nodejs#2892]
We've received reports that v3.36.0 of the Node.js agent is sending invalid data to APM Server.

Specifically, APM Server reports `400 - data validation error` and `validation error: 'metadata' required`

**TODO: To Reproduce**

Steps to reproduce the behavior: 
1. Use this config '...'
2. Then call '....'
3. Then do '....'

**Expected behavior**

**Environment (please complete the following information)**

- OS: [e.g. Linux]
- Node.js version:
- APM Server version:
- Agent version:

**How are you starting the agent? (please tick one of the boxes)**

- [ ] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

TODO

**Comment by trentm** [comment]
There isn't any specific information to go on, and I've heard of no other similar reports.
If this comes up again, then we need to get some logging details from the agent (or perhaps incoming request body capture on the APM server-side -- though I don't think we do that).
