### ISSUE TITLE
Add support for intake API v2

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#471]
### Needed to be released

- [x] Implement core logic (PR #465)
- [x] Move truncation logic to [apm-nodejs-http-client](https://github.com/elastic/apm-nodejs-http-client) (PR #498)
- [x] Document `apiRequestSize` and `apiRequestTime` (PR #499)
- [x] Re-add support for `DEBUG_PAYLOAD` (PR #500)
- [x] Create benchmarks showing difference between old and new API
- [x] Update HTTP client to use new endpoints (PR elastic/apm-nodejs-http-client#18)
- [x] Update filtering API (PR #579)
- [x] Add mock trace-id's (PR #584)
- [x] Reenable schema tests using new JSON schemas from the v2 API (PR #585)
- [x] Update APM Server json schema links to point to the `master` branch instead of `v2`
- [x] Write upgrade docs from v1.x to v2.x (PR #631)
- [x] Stop sending data to the server [if the server responds prematurely](https://github.com/elastic/apm-server/issues/1298#issuecomment-415704054) (PR elastic/apm-nodejs-http-client#32
- [x] Ensure there's no remaining TODO's in the code related to v2
- [x] Update doc links to APM Server documentation (in ~~[addFilter](https://github.com/elastic/apm-agent-nodejs/blob/master/docs/agent-api.asciidoc#apmaddfilter)~~ + [metadata](https://github.com/elastic/apm-agent-nodejs/blob/master/docs/agent-api.asciidoc#metadata)) (server issue: elastic/apm-server#1329, PR #672)
- [x] Ensure `package.json` dependencies point to npm and not temporary GitHub branches (PR #670)

### Can be postponed to a minor or patch release

- [x] Fix bug that wrongly counts uncompressed bytes of HTTP body instead of compressed (PR elastic/apm-nodejs-http-client#25)
- [ ] Implement grace period algorithm in case of APM Server errors if it's offline (PR elastic/apm-nodejs-http-client#17)
- [ ] Automatically run benchmarks ([WIP](https://github.com/watson/apm-agent-nodejs/commit/2ce04333a12a106dada46018e24e42c76eccd0f5))
- [x] Parse returned json document in case of errors (PR #671)
- [ ] Don't discard spans started after transaction ended

### Nice to have

- [ ] Only flush if the error being sent is an uncaught exception

**Comment by roncohen** [comment]
great to have a list Thomas 👍 
What about benchmarks?

**Comment by watson** [comment]
@roncohen good call. I've added it

**Comment by watson** [comment]
v2 is now done. I've moved all open tasks to their own separate issues
